import { execFileSync } from 'node:child_process'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { instrument, type BeforeSendFn, type MCPAnalyticsOptions } from '@posthog/mcp'
import { PostHog, type EventMessage, type PostHogOptions } from 'posthog-node'

import { redactText } from '@social-publisher/telemetry'

import { clientOf, outcomeOf, type MeterOptions } from './metering.ts'

/**
 * PostHog MCP Analytics: the `$mcp_tool_call` events behind PostHog's MCP
 * Analytics pages (project 297949, EU), next to our own `mcp_call` event
 * (packages/telemetry analytics.ts), which stays.
 *
 * WHY @posthog/mcp + posthog-node (both pinned exactly in package.json):
 * MCP Analytics reads PostHog's own `$mcp_*` event shape, which only its SDK
 * produces; the owner asked for this instrumentation by name (2026-10-08).
 * Versions and licences, checked in node_modules on 2026-10-08:
 *   - @posthog/mcp 0.22.1 (beta): package.json says MIT; the LICENSE file it
 *     ships is the posthog-js repository's (Apache-2.0, with MIT-licensed parts
 *     from AgentCat/MCPcat). Both are permissive. 0.22.1, not 0.22.2, because
 *     0.22.2 was younger than pnpm's minimum release age.
 *   - posthog-node 5.55.0, @posthog/core 1.57.1, @posthog/types 1.415.1: MIT
 *     in package.json, the same LICENSE file.
 * This reverses part of the Phase 2 choice ("no posthog-node"): the reason
 * given there was that no third-party code should run in a process holding
 * platform tokens. That cost is accepted here for MCP Analytics only, and is
 * contained: the client gets nothing but the events below, after our filter.
 *
 * What the SDK would send by default, and what we let out. Read from the
 * package source (src/extensions/posthog-events.ts, capture.ts, sink.ts,
 * instrumentation.ts, internal.ts) on 2026-10-08:
 *   - By default it records each call's arguments (`$mcp_parameters`) and
 *     result (`$mcp_response`), the error text (`$mcp_error_message`, and a
 *     `$exception` event with a stack), the HTTP User-Agent and
 *     `x-anthropic-client` headers, declared argument names (`$mcp_input_keys`),
 *     and a `$identify` event whose payload is the whole request plus its
 *     `extra` (which on HTTP holds the request headers).
 *   - The options below switch off everything that would change a tool's
 *     input schema (`context`, `conversation_id`, `llm_model`, the virtual
 *     `get_more_tools` / `send_feedback` tools) and exception events.
 *   - `beforeSend` (mcpAnalyticsBeforeSend) then keeps two events and an
 *     allow-list of properties, checks every value, and drops everything
 *     else. The posthog-node client applies the same allow-list again
 *     (`before_send`), so nothing reaches the wire past both.
 * Written up for the privacy policy in architecture/2026-10-08-plans-usage-
 * analytics-hosting.md, "Privacy notes (analytics)".
 */

/** The only events this client sends. */
export const MCP_ANALYTICS_EVENTS = ['$mcp_tool_call', '$mcp_initialize'] as const

/**
 * The only properties that leave the process on those events. Adding one is a
 * privacy decision: it belongs in the privacy notes too.
 */
export const MCP_ANALYTICS_PROPERTIES = [
  '$mcp_tool_name',
  '$mcp_resource_name', // the same value as $mcp_tool_name on a tool call
  '$mcp_duration_ms',
  '$mcp_is_error',
  '$mcp_error_type', // our catalogue code (e.g. TOKEN_EXPIRED) or UNKNOWN, never the message
  '$mcp_client_name',
  '$mcp_client_version',
  '$mcp_protocol_version',
  '$mcp_server_name',
  '$mcp_server_version',
  '$mcp_server_build',
  '$mcp_source', // the constant posthog_mcp_analytics, which marks the event as MCP Analytics'
  '$session_id', // opaque, generated by the SDK (ses_…)
  '$process_person_profile', // false on the rare event with no tenant
  '$geoip_disable', // always true
] as const

const EVENTS = new Set<string>(MCP_ANALYTICS_EVENTS)
const PROPERTIES = new Set<string>(MCP_ANALYTICS_PROPERTIES)

/** cuid and uuid shapes, as in analytics.ts; an email or a name never passes. */
const DISTINCT_ID = /^[A-Za-z0-9_-]{8,64}$/
/** The SDK's session ids: ses_ and a uuidv7, or ses_ and 32 hex characters. */
const SESSION_ID = /^ses_[0-9a-f-]{16,40}$/
/** A short plain token, as in analytics.ts: no URL, query string, email or markup fits. */
const PLAIN_VALUE = /^[A-Za-z0-9 ._:+/()-]{1,120}$/
const MAX_DURATION_MS = 24 * 60 * 60 * 1000
/** Git short or full SHA. */
const BUILD = /^[0-9a-f]{7,40}$/

function plain(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined
  const trimmed = value.trim().slice(0, 120)
  if (!PLAIN_VALUE.test(trimmed) || trimmed.includes('//')) return undefined
  // Anything the log redactor would touch is a credential shape: not sent.
  return redactText(trimmed) === trimmed ? trimmed : undefined
}

/** The tool's own outcome, read the way metering reads it (metering.ts outcomeOf). */
function outcomeFrom(properties: Record<string, unknown>): { isError: boolean; code?: string } {
  const sdkSaysError = properties.$mcp_is_error === true
  const response = properties.$mcp_response
  // Our tools report most failures as an ordinary result whose first line is
  // "[CODE] …", without the SDK's isError flag, so the response is read first.
  if (response !== null && typeof response === 'object') {
    const outcome = outcomeOf(response)
    if (!outcome.ok) return { isError: true, code: outcome.errorCode ?? 'UNKNOWN' }
  }
  if (sdkSaysError) {
    // A thrown error, or the SDK's own refusal (unknown tool, invalid arguments).
    // The message can quote arguments, so only a catalogue code is taken from it.
    const message = typeof properties.$mcp_error_message === 'string' ? properties.$mcp_error_message : ''
    const outcome = outcomeOf({ content: [{ type: 'text', text: message }], isError: true })
    return { isError: true, code: outcome.errorCode ?? 'UNKNOWN' }
  }
  return { isError: false }
}

/**
 * The final filter on every event the MCP Analytics SDK builds, run after its
 * own sanitising and before posthog-node queues the event. Exported for tests.
 *
 * Keeps `$mcp_tool_call` and `$mcp_initialize` only; on those, keeps only
 * MCP_ANALYTICS_PROPERTIES with checked values. The tool's result is read here
 * (in memory) for its catalogue code and is then dropped with everything else.
 */
export function mcpAnalyticsBeforeSend(knownTool: (name: string) => boolean): BeforeSendFn {
  return (event) => {
    if (!EVENTS.has(event.event)) return null
    if (typeof event.distinct_id !== 'string' || !DISTINCT_ID.test(event.distinct_id)) return null

    const input = event.properties ?? {}
    const out: Record<string, unknown> = { $mcp_source: 'posthog_mcp_analytics', $geoip_disable: true }

    if (input.$process_person_profile === false) out.$process_person_profile = false
    if (typeof input.$session_id === 'string' && SESSION_ID.test(input.$session_id)) out.$session_id = input.$session_id

    for (const key of ['$mcp_client_name', '$mcp_client_version', '$mcp_protocol_version', '$mcp_server_name', '$mcp_server_version'] as const) {
      const value = plain(input[key])
      if (value !== undefined) out[key] = value
    }
    if (typeof input.$mcp_server_build === 'string' && BUILD.test(input.$mcp_server_build)) {
      out.$mcp_server_build = input.$mcp_server_build
    }
    const duration = input.$mcp_duration_ms
    if (typeof duration === 'number' && Number.isFinite(duration) && duration >= 0 && duration <= MAX_DURATION_MS) {
      out.$mcp_duration_ms = Math.round(duration)
    }

    if (event.event === '$mcp_tool_call') {
      // A client may call a name we never registered; that name is its text, not ours.
      const requested = input.$mcp_tool_name
      const tool = typeof requested === 'string' && knownTool(requested) ? requested : 'unknown_tool'
      out.$mcp_tool_name = tool
      out.$mcp_resource_name = tool
      const outcome = outcomeFrom(input)
      out.$mcp_is_error = outcome.isError
      if (outcome.code !== undefined) out.$mcp_error_type = outcome.code
    } else if (typeof input.$mcp_is_error === 'boolean') {
      out.$mcp_is_error = input.$mcp_is_error
    }

    return { distinct_id: event.distinct_id, event: event.event, properties: out, timestamp: event.timestamp, type: 'capture' }
  }
}

/**
 * The same allow-list at the client, the last step before the wire: whatever
 * route an event takes into this posthog-node client, an event or property not
 * on the lists does not leave. After this hook posthog-node adds only three
 * constants about itself: $lib (posthog-node-mcp), $lib_version and
 * $is_server (true); the wire test in mcp-analytics.test.ts holds it to that.
 */
function clientGuard(message: EventMessage | null): EventMessage | null {
  if (message === null || !EVENTS.has(message.event)) return null
  const properties: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(message.properties ?? {})) {
    if (PROPERTIES.has(key)) properties[key] = value
  }
  properties.$geoip_disable = true
  const { groups: _groups, ...rest } = message
  return { ...rest, properties }
}

export interface McpAnalyticsSettings {
  readonly apiKey?: string | undefined
  readonly host?: string | undefined
  /** Told about failures once. Must not throw; never given the key. */
  readonly onError?: (message: string) => void
  /** Tests only: a fake fetch, so nothing reaches the network. */
  readonly fetch?: PostHogOptions['fetch']
  /** Tests only. */
  readonly flushAt?: number
}

/**
 * The posthog-node client for MCP Analytics, one per process, or undefined
 * when there is no usable key (then nothing is instrumented, silently).
 * Only a project key (phc_…) and an https host are used, as in createAnalytics;
 * neither refusal prints the value.
 */
export function createMcpAnalyticsClient(settings: McpAnalyticsSettings): PostHog | undefined {
  const key = settings.apiKey?.trim() ?? ''
  if (key === '') return undefined
  const report = onceOnly(settings.onError)
  if (!key.startsWith('phc_')) {
    report('POSTHOG_KEY is not a PostHog project key (it should start with phc_); MCP Analytics is off')
    return undefined
  }
  const host = (settings.host ?? '').trim()
  if (!/^https:\/\/[^\s/?#]+\/?$/.test(host)) {
    report('POSTHOG_HOST must be an https address with no path, such as https://eu.i.posthog.com; MCP Analytics is off')
    return undefined
  }
  const client = new PostHog(key, {
    host,
    flushAt: settings.flushAt ?? 20,
    flushInterval: 10_000,
    // Bounded like our own client: an unreachable PostHog must not grow memory.
    maxQueueSize: 1_000,
    requestTimeout: 5_000,
    // Lossy by design (the tool_calls table is the record): a failed batch is not retried.
    fetchRetryCount: 0,
    disableGeoip: true,
    enableExceptionAutocapture: false,
    before_send: clientGuard,
    ...(settings.fetch !== undefined ? { fetch: settings.fetch } : {}),
  })
  client.on('error', (error: unknown) => report(`MCP Analytics could not send events: ${messageOf(error)}`))
  return client
}

/** What createAdsPilotServer needs to instrument a server. */
export interface McpAnalyticsSetup {
  readonly client: PostHog
  /** The git SHA this server was built from, when known (resolveServerBuild). */
  readonly serverBuild?: string | undefined
}

/**
 * Instruments one server. Called by createAdsPilotServer after metering is
 * installed and before any tool exists, on both transports.
 *
 * Composition with metering: metering wraps the handler at registration
 * (tool / registerTool); the SDK then wraps the stored registry entry around
 * that metered handler and wraps the tools/call request handler. A call runs
 * SDK capture → MCP validation → metered handler → tool, so it is counted once
 * and captured once (metering.test.ts / mcp-analytics.test.ts).
 */
export function instrumentMcpAnalytics(server: McpServer, setup: McpAnalyticsSetup, meter: MeterOptions): void {
  const registered = () => (server as unknown as { _registeredTools: Record<string, unknown> })._registeredTools
  const options: MCPAnalyticsOptions = {
    // Each of these would add an argument to every tool's input schema or add a tool.
    context: false,
    enableConversationId: false,
    captureModel: false,
    reportMissing: false,
    collectFeedback: false,
    // A stack and an error message can quote the user's content.
    enableExceptionAutocapture: false,
    // Never record argument names either (the default records declared ones).
    shouldRecordInputKey: () => false,
    // Our tenant id, the same distinct_id as mcp_call; never an email. No $set:
    // plan and industry already reach the person through mcp_call.
    identify: async () => {
      try {
        const account = await meter.account()
        return DISTINCT_ID.test(account.tenantId) ? { distinctId: account.tenantId } : null
      } catch {
        return null // metering logs the same failure; the event goes out anonymous
      }
    },
    // The hosted server is stateless: a tool call's server never saw initialize,
    // so the client is the one remembered for this token (hosted-server.ts),
    // exactly as mcp_call reports it. Overrides the SDK's own (empty) value.
    eventProperties: (request) => {
      if (request.method !== 'tools/call') return null
      const client = clientOf(server, meter)
      const props: Record<string, unknown> = {}
      if (client?.name !== undefined) props.$mcp_client_name = client.name
      if (client?.version !== undefined) props.$mcp_client_version = client.version
      return props
    },
    beforeSend: mcpAnalyticsBeforeSend((name) => Object.prototype.hasOwnProperty.call(registered(), name)),
    ...(setup.serverBuild !== undefined ? { serverBuild: setup.serverBuild } : {}),
    // The SDK's own warnings are not wanted on stdout (on stdio that is the protocol) or in Slack.
    logger: () => {},
  }
  instrument(server, setup.client, options)
}

/**
 * The git SHA of this build, for `$mcp_server_build`, or undefined.
 * The server sets BUILD_SHA (docker-compose.yml, from the release's commit);
 * the PC's stdio server asks git about its own checkout. Never throws.
 */
export function resolveServerBuild(env: NodeJS.ProcessEnv = process.env): string | undefined {
  const fromEnv = env.BUILD_SHA?.trim().toLowerCase()
  if (fromEnv !== undefined && fromEnv !== '') return BUILD.test(fromEnv) ? fromEnv : undefined
  try {
    const sha = execFileSync('git', ['rev-parse', '--short=12', 'HEAD'], {
      cwd: dirname(fileURLToPath(import.meta.url)),
      encoding: 'utf8',
      timeout: 2_000,
      stdio: ['ignore', 'pipe', 'ignore'],
      windowsHide: true,
    }).trim()
    return BUILD.test(sha) ? sha : undefined
  } catch {
    return undefined
  }
}

function onceOnly(report: ((message: string) => void) | undefined): (message: string) => void {
  let told = false
  return (message) => {
    if (told || report === undefined) return
    told = true
    try {
      report(message)
    } catch {
      // A failing reporter must not break the caller.
    }
  }
}

function messageOf(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}
